### ISSUE TITLE
ctrl+r can not only catch php function

### ISSUE THREAD

**Issue by godcong** [atom/symbols-view#192] opened 2016-09-01 09:45 UTC
Steps to Reproduce

[First Step]

open a php file

<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;

abstract class Job
{
    /*
    |--------------------------------------------------------------------------
    | Queueable Jobs
    |--------------------------------------------------------------------------
    |
    | This job base class provides a central location to place any logic that
    | is shared across all of your jobs. The trait included with the class
    | provides access to the "onQueue" and "delay" queue helper methods.
    |
    */

```
use Queueable;
```

}
[Second Step]
press Ctrl+R want jump into a function
[and so on...]
displayed content　is:

/_-----------
/ Job
/ Line:7
/-----------
/ providers
/ Line:14
/-----------_/
Expected behavior: [What you expected to happen]
no data displayed or only class name displayed

Actual behavior: [What actually happened]
a comment displayed

/_-----------
/  providers
/  Line:14
/-----------_/
Versions
atom 1.9.7
both in:
atom 1.11.0beta0
symbols-view 0.113.1
file code type: crlf utf-8 php
i used an us keyboard

**Comment by anotherZero** [comment] 2016-09-15 21:51
I have a similar disappointment when using ctrl+r in that it finds ALL symbols, instead of just functions (at least in php files).  It would be nice to have some control over this behavior.

**Comment by mcdado** [comment] 2016-12-01 09:59
Probably duplicate of https://github.com/atom/symbols-view/issues/175.

**Comment by Ben3eeE** [comment] 2016-12-01 13:57
Thanks @mcdado, closing as a duplicate of #175

**Closed by Ben3eeE** 2016-12-01 13:57 UTC
