### ISSUE TITLE
Jumpto Symbol should scroll function into full view

### ISSUE THREAD

**Issue by raptor235** [atom/symbols-view#161] opened 2016-03-26 23:12 UTC
Currently if you jump to symbol it will jump to the function but the function is at the bottom of the view about 5 lines from the bottom... the function should be fully visible from the top of the view.

**Comment by SirCameron** [comment] 2016-11-26 08:35
I second this :) I wrote a long suggestion about it on the main Atom repo and was told to post it here.
With this, developers will be able to scan and skip through code much more easily.

**Comment by calebmeyer** [comment] 2017-10-17 19:48
Note that vim-mode-plus has a command we might be able to replicate that would help with this:
`vim-mode-plus:scroll-cursor-to-top-leave`

I can't for the life of me find what source is powering it though.

**Comment by Ben3eeE** [comment] 2017-10-18 12:54
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/symbols-view/issues/132. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-10-18 12:54 UTC
Labels: duplicate
