### ISSUE TITLE
Can't find tagfile

### ISSUE THREAD

**Issue by paradox460** [atom/symbols-view#182] opened 2016-06-08 18:25 UTC
Many users use a git post-commit hook to generate tag files, which get saved in `.git`. Plugins such as fugitive.vim have configuration options to allow for the tag file to be in different locations, and take into account path.

Atom does not allow this to be changed, its hardcoded into https://github.com/atom/symbols-view/blob/master/lib/tag-reader.coffee.

Furthermore, creating a softlink to the tags file does not work, as all tag urls are `../` based

**Comment by 50Wliu** [comment] 2016-06-08 19:06
This is a duplicate of #77 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-06-08 19:06 UTC
