### ISSUE TITLE
Uncaught Error: Module did not self-register. ELECTRON_ASAR.js

### ISSUE THREAD

**Issue by cbuteau** [atom/symbols-view#216] opened 2017-03-30 14:01 UTC
## Stack
ELECTRON_ASAR.js:168
Hide Stack Trace
Error: Module did not self-register.
    at Error (native)
    at process.module.(anonymous function) (ELECTRON_ASAR.js:168:20)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:182:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\cbu1\AppData\Local\atom\app-1.15.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\cbu1\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\ctags\lib\ctags.js:4:10)
    at Object.<anonymous> (C:\Users\cbu1\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\ctags\lib\ctags.js:60:4)
    at Module._compile (C:\Users\cbu1\AppData\Local\atom\app-1.15.0\resources\app.asar\src\native-compile-cache.js:109:30)
    at Object.value [as .js] (C:\Users\cbu1\AppData\Local\atom\app-1.15.0\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\cbu1\AppData\Local\atom\app-1.15.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\cbu1\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\symbols-view\lib\tag-reader.js:11:14)
    at Module._compile (C:\Users\cbu1\AppData\Local\atom\app-1.15.0\resources\app.asar\src\native-compile-cache.js:109:30)
    at Object.value [as .js] (C:\Users\cbu1\AppData\Local\atom\app-1.15.0\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\cbu1\AppData\Local\atom\app-1.15.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\cbu1\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\symbols-view\lib\go-to-view.js:23:18)
    at Module._compile (C:\Users\cbu1\AppData\Local\atom\app-1.15.0\resources\app.asar\src\native-compile-cache.js:109:30)
    at Object.value [as .js] (C:\Users\cbu1\AppData\Local\atom\app-1.15.0\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\cbu1\AppData\Local\atom\app-1.15.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.createGoToView (file:///C:/projects/atom/out/app/node_modules/symbols-view/lib/main.js:80:22)
    at atom-text-editor.symbolsViewGoToDeclaration (file:///C:/projects/atom/out/app/node_modules/symbols-view/lib/main.js:18:14)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\cbu1\AppData\Local\atom\app-1.15.0\resources\app.asar\src\command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (C:\Users\cbu1\AppData\Local\atom\app-1.15.0\resources\app.asar\src\command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\cbu1\AppData\Local\atom\app-1.15.0\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\cbu1\AppData\Local\atom\app-1.15.0\resources\app.asar\src\atom-environment.js:1168:28)
    at EventEmitter.outerCallback (C:\Users\cbu1\AppData\Local\atom\app-1.15.0\resources\app.asar\src\application-delegate.js:325:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Hello,
I just wanted goto declaration to work.
http://stackoverflow.com/questions/32083136/how-can-i-get-atom-ios-go-to-declaration-to-really-do-that
Reading this I tried the atom-ctags project.

I first installed it and ran into this problem.
https://github.com/yongkangchen/atom-ctags/issues/145
Reading the issue I found the most common fix was to restart Atom and reinstall the atom-ctags package.
So I did so and it succeeded in installing.
it also popped up a warning that it would disable symbols view.
However when I did a right-click rebuild symbols and a right-click goto declaration I ran into the current problem.
Which informed was this bug.
https://github.com/atom/symbols-view/issues/110

But it is not because it is a completely different module.
So I am creating a new issue.
You can investigate and find it is a dupe.

### Steps to Reproduce

See above.

**Expected behavior:** [What you expect to happen]
Goto Declaration.

**Actual behavior:** [What actually happens]
Crash Warning.

**Reproduces how often:** [What percentage of the time does it reproduce?]
3 times in a row...I am done reproing....
I will use when you tell me workaround or new package to install.

### Versions

λ atom --version

Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

e:\WS\CBU1_2017x_setTypes\ENXNav.tst\FunctionTests\TestCases
λ apm --version
apm  1.15.3
npm  3.10.5
node 4.4.5 ia32
python 3.5.1
git 2.6.1.windows.1
visual studio 2012

Windows 7 Enterprise Service Pack 1
64 bit

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment] 2017-03-31 01:58
> You can investigate and find it is a dupe.

Thanks for checking the previous issues!  Not a lot of people do that :).  This is in fact a duplicate of #110 because `ATOM_SHELL_ASAR` was renamed to `ELECTRON_ASAR`.

**Closed by 50Wliu** 2017-03-31 01:59 UTC

**Comment by cbuteau** [comment] 2017-03-31 11:18
No problem.
It sounded very similar but I really didnt have time to investigate.
I opened the file twice (split right) so I did not have to jump to the fuctions.
