### ISSUE TITLE
Methods called 'save' or starting with 'save' are not been found

### ISSUE THREAD

**Issue by rogeriotaques** [atom/symbols-view#130] opened 2015-11-10 00:52 UTC
Whenever I have any method/function called save, or which name starts by save, I can't find it using the cmd-r command. I am just able to find it using the default 'search' feature.

**Comment by mshenfield** [comment] 2015-12-06 23:12
I'm able to add methods called `save` or starting with `save` in a CoffeeScript project and find them using `symbols-view:go-to-declaration` and `symbols-view:toggle-project-symbols`. I've commited the tags up to a remote branch here if you want to give it a shot in your editor. I am running Atom `1.2.4

**Comment by rogeriotaques** [comment] 2015-12-07 01:30
MacOS 10.10.5
Atom 1.2.4
Symbols-view 0.110.0
Language PHP, Javascript

Code snippet:

```
public function save (array $data = array(), $id = NULL) {
   // logic goes here ...

   $error = $this->db->error();

   if (is_array($error) && $error['code'] > 0) {
      throw new Exception("Impossible to save.", 1);
   }

   return $id;
} // save
```

**Comment by mshenfield** [comment] 2015-12-08 08:08
It looks like this is actually a duplicate of #103. If you remove the array default function arguments, e.g.

```php
public function save (array $data, $id = NULL) {
```

symbols-view is able to find it using `symbols-view:toggle-file-view`.  

There are two issues at play. Underneath the covers Atom uses [`ctags`](http://ctags.sourceforge.net/) to generate file-level symbols, which ships under symbols-view's [vendor folder](https://github.com/atom/symbols-view/tree/v0.110.1/vendor). It seems like there are [several issues](http://sourceforge.net/p/ctags/bugs/search/?q=php) with PHP parsing for this version of `ctags`, but it won't be fixed because the SourceForce `ctags` is no longer actively maintained. These issues include incorrectly identifying default function parameters as free variables.

The second is that symbols-view only allows 1 symbol definition per line inside of  `symbols-view:toggle-file-symbols` https://github.com/atom/symbols-view/blob/v0.110.1/lib/tag-generator.coffee#L76. In your example, `array $data = array()` is being parsed first, preventing `save` from being included in the tags list.

For an immediate fix, you can try installing [`universal-ctags`](https://ctags.io/), an actively developed fork of `ctags` that [fixes](https://github.com/universal-ctags/ctags/issues/21) many of the PHP issues. The installation instructions for OSX are available [here](https://github.com/universal-ctags/ctags/blob/master/docs/osx.rst). For the commands involving a user generated tag file (everything but `symbols-view:toggle-file-view`) this will now allow you to correctly navigate to methods like `save`. For `symbols-view:toggle-file-view`, assuming you now have universal-ctags installed at `/usr/local/bin/ctags`, running the following will symlink the `ctags` symbols-view uses internally for that function to `universal-ctags`.

```bash
cp /Applications/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/symbols-view/vendor/ctags-darwin /Applications/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/symbols-view/vendor/exuberant-ctags-darwin

ln -s -f /usr/local/bin/ctags /Applications/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/symbols-view/vendor/ctags-darwin
```

and if you want to go back to normal

```bash
mv -f /Applications/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/symbols-view/vendor/exuberant-ctags-darwin /Applications/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/symbols-view/vendor/ctags-darwin
```
`
`

**Closed** 2020-10-09 03:15 UTC
Labels: needs-reproduction
