### ISSUE TITLE
Enhancement: when scrolling to symbol, center it in the buffer

### ISSUE THREAD

**Issue by lzkelley** [atom/symbols-view#132] opened 2015-11-17 17:34 UTC
Currently scrolling to a symbol places the symbol at the bottom of the buffer.  It seems like it would be better to place it in the center, or even towards the top, of the open file.

**Comment by lloiser** [comment] 2015-11-19 21:12
+1
looking through the code revealed that it actually tries to do so...
https://github.com/atom/symbols-view/blob/efe5c4d5dcb24d09fbec861842781c54c94a3ea7/lib/symbols-view.coffee#L90

**Comment by mshenfield** [comment] 2015-12-06 15:13
It looks like `setCursorBufferPosition` on L91 is thrashing `scrollToBufferPosition` on L90.

Try running the following in Atom dev console (with the file of your choice, I have symbols-view project open in Aton) to see in action:

```
path = require('path')
position = [69, 0]
file = path.join(atom.project.getPaths()[0], "lib", "symbols-view.coffee")
atom.workspace.open(file).then(function() {
editor = atom.workspace.getActiveTextEditor()
editor.scrollToBufferPosition(position, {center: true})
editor.setCursorBufferPosition(position)
})
```

Passing `autoscroll: false` in the options for `setCursorBufferPosition` fixes this.

```
editor.setCursorBufferPosition(position, {autoscroll: false})
```

**Comment by mshenfield** [comment] 2015-12-06 23:08
This actually doesn't solve the full issue - underneath the covers `moveToFirstCharacterInLine` *also* requests an `autoscroll`. There isn't a way to turn this off through any of the [`Cursor` methods](https://atom.io/docs/api/v1.2.4/Cursor#instance-moveToFirstCharacterOfLine) , including the one `TextEditor` proxies for `moveToFirstCharacterInLine`.

It seems like there's a bigger issue where sequential scroll requests override each other. For example, adding another call to `scrollToBufferPosition` after `moveToFirstCharacterOfLine` actually corrects the scrolling behavior to center on the variable. 

It looks like the sequential method calls are both updating the `TextEditorPresenter.state` before the next animation frame is notified by an event to update the UI in response.

I'm updating this to the following, which *looks* like it is doing the right thing, even though it relies on the the call to `scrollToCursorPosition` to override the previous, implicit autoscroll in `moveToFirstCharacerOfLine()`. This will have the desired behavior of centering the editor on the symbol where possible.
```coffee
moveToPosition: (position, beginningOfLine=true) ->
  if editor = atom.workspace.getActiveTextEditor()
    editor.setCursorBufferPosition(position, autoscroll: false)
    editor.moveToFirstCharacterOfLine() if beginningOfLine
    # Override scrolling in above line to center editor, see issue #132
    editor.scrollToCursorPosition(center: true)
```

**Comment by stwr667** [comment] 2016-08-15 01:11
+1 for this bugfix.

**Comment by adamreisnz** [comment] 2017-10-17 19:11
+1 for this fix... it seems like a minor thing to tackle, yet it would using this so much more convenient as the thing you're looking for will scroll properly into view.

**Comment by mshenfield** [comment] 2017-10-18 01:30
Will take another look this week.

**Comment by adamreisnz** [comment] 2017-10-18 01:51
Awesome, thanks! 🎉

**Comment by calebmeyer** [comment] 2017-10-18 12:56
Vim mode plus has commands that do this: https://github.com/t9md/atom-vim-mode-plus/blob/f7ffd42ddc1557973eff4d3edd39557252162c78/lib/misc-command.js#L373

**Comment by mshenfield** [comment] 2017-10-20 15:36
Updated to ES6.  Tested manually and confirmed the old behavior of thrashing is still happening without the fix, and fixed with the fix.

**Comment by iangilman** [comment] 2017-11-19 20:32
@mshenfield Fantastic! When should we expect to see it updated in this package?

**Comment by 50Wliu** [comment] 2017-11-19 21:47
@mshenfield do you have a PR for your fix?  I can't seem to find it.

**Comment by mshenfield** [comment] 2017-12-01 02:18
https://github.com/atom/symbols-view/pull/136.

**Closed** 2017-12-10 15:55 UTC
Labels: bug, triaged
