### ISSUE TITLE
Go To Declaration doesn't correctly pass {center: true} option

### ISSUE THREAD

**Issue by DamnedScholar** [atom/symbols-view#205] opened 2017-01-05 22:57 UTC
[From the forums](https://discuss.atom.io/t/symbols-view-screen-center-on-symbol-definition/37790).

When you jump to the next or previous symbol, [this](https://github.com/atom/symbols-view/blob/master/lib/symbols-view.js#L135) is the code that changes the buffer position, using the [`editor.scrollToBufferPosition()`](https://atom.io/docs/api/v1.12.9/TextEditor#instance-scrollToBufferPosition) function. The `{center: true}` bit *should* make the buffer center around that position. You can test this by opening a file of sufficient length (let's say 200 lines) and opening the dev tools via `View -> Developer -> Toggle Developer Tools`, then you can enter `atom.workspace.getActiveTextEditor().scrollToBufferPosition([100,0], {center: true})`. When I do that, I get line 100 right in the center of my screen. If I enter `atom.workspace.getActiveTextEditor().scrollToBufferPosition([100,0], {center: false})`, then line 100 is either near the top or near the bottom, same as the behavior of the `symbols-view` package. The default for the `center` option is false, so it seems like that object isn't going through somehow, and the default is being used. I'm not sure why it's not working like it should.

**Comment by 50Wliu** [comment] 2017-01-05 23:05
Looks like a duplicate of #132?

**Comment by DamnedScholar** [comment] 2017-01-05 23:21
Yes, it is. Sorry, didn't see that.

**Closed** 2017-01-06 03:20 UTC
Labels: more-information-needed
