### ISSUE TITLE
Uncaught Error: Cannot find module './.ctags'

### ISSUE THREAD

**Issue by chriswins2much** [atom/symbols-view#67] opened 2015-01-03 16:36 UTC
This happens when navigating to:
`Packages -> Symbols -> File Symbols`

**Atom Version**: 0.165.0
**System**: Microsoft Windows 8.1
**Thrown From**: [symbols-view](https://github.com/atom/symbols-view) package, v0.70.0

### Stack Trace

Uncaught Error: Cannot find module './.ctags'

```
At module.js:346

Error: Cannot find module './.ctags'
  at Module._resolveFilename (module.js:344:15)
  at Function.Module._resolveFilename (c:\Users\user\AppData\Local\atom\app-0.165.0\resources\app\src\module-cache.js:380:52)
  at Function.require.resolve (module.js:396:19)
  at TagGenerator.module.exports.TagGenerator.generate (c:\Users\user\AppData\Local\atom\app-0.165.0\resources\app\node_modules\symbols-view\lib\tag-generator.js:89:34)
  at FileView.module.exports.FileView.generateTags (c:\Users\user\AppData\Local\atom\app-0.165.0\resources\app\node_modules\symbols-view\lib\file-view.js:100:62)
  at FileView.module.exports.FileView.populate (c:\Users\user\AppData\Local\atom\app-0.165.0\resources\app\node_modules\symbols-view\lib\file-view.js:95:21)
  at FileView.module.exports.FileView.toggle (c:\Users\user\AppData\Local\atom\app-0.165.0\resources\app\node_modules\symbols-view\lib\file-view.js:72:14)
  at atom-text-editor.editorSubscription.atom.commands.add.symbols-view:toggle-file-symbols (c:\Users\user\AppData\Local\atom\app-0.165.0\resources\app\node_modules\symbols-view\lib\main.js:21:43)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (c:\Users\user\AppData\Local\atom\app-0.165.0\resources\app\src\command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (c:\Users\user\AppData\Local\atom\app-0.165.0\resources\app\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (c:\Users\user\AppData\Local\atom\app-0.165.0\resources\app\src\command-registry.js:156:19)
  at Ipc.<anonymous> (c:\Users\user\AppData\Local\atom\app-0.165.0\resources\app\src\window-event-handler.js:65:30)
  at Ipc.emit (events.js:107:17)
  at process.<anonymous> (c:\Users\user\AppData\Local\atom\app-0.165.0\resources\atom\renderer\api\lib\ipc.js:22:29)
  at process.emit (events.js:110:17)

```

### Commands

```
 12x -1:23.8 core:backspace (input.hidden-input)
     -0:00.0 symbols-view:toggle-file-symbols (input.hidden-input)
```

### Config

```
{
  "core": {
    "disabledPackages": [
      "helium",
      "ide-haskell"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

/cc @atom/core

**Comment by kevinsawicki** [comment] 2015-01-05 18:02
Duplicate of https://github.com/atom/symbols-view/issues/63

**Closed by kevinsawicki** 2015-01-05 18:02 UTC

**Comment by mrkhanakia** [comment] 2015-11-01 05:18
Hi
There can 2 reason that you are getting above error
1. ctags module is not installed
2. if ctags module installed correctly then NODE_PATH is not set which is causing error.
So i have Centos server and my shared node_modules are installed in that directory /usr/local/lib/node_modules

So i did SSH in my system as normal user (Not root user) and then did fire the following command
export NODE_PATH=/usr/local/lib/node_modules
