### ISSUE TITLE
No Symbols Found using ES2015 const and => for functions

### ISSUE THREAD

**Issue by dannyfritz** [atom/symbols-view#174] opened 2016-04-29 01:47 UTC
I get `No Symbols Found` on [this file](https://github.com/dannyfritz/handemade-quake-js/blob/0676bef/main/electronquake.js).
- Atom v1.7.3
- Windows 10 x64
- Happens in Safe-Mode (Will be related to the [JS Grammar](https://github.com/atom/language-javascript/tree/master/grammars))

![atom_2016-04-28_07-53-24](https://cloud.githubusercontent.com/assets/315788/14906577/12d0b91c-0d7a-11e6-824c-ab79e5b13b66.png)

**Comment by dperetti** [comment] 2016-06-01 23:53
Also doesn't work (and should!) without the `const `, like :
```
_onChange = () => {
    ...
}
```

**Comment by iolsen** [comment] 2016-11-17 01:11
So the reason for this behavior is the [regular expressions we're feeding to ctags](https://github.com/atom/symbols-view/blob/master/lib/ctags-config#L93).

As a quick way to get this working slightly better, If you have a `.ctags` file in your home directory with additional expressions defined, Atom's call to ctags will pick them up. At least on Mac. I grabbed [these](https://dance.computer.dance/posts/2015/04/using-ctags-on-modern-javascript.html) and added them to my `~/.ctags` file:

```
--regex-JavaScript=/[ \t.]([A-Z][A-Z0-9._$]+)[ \t]*[=:][ \t]*([0-9"'\[\{]|null)/\1/n,constant/

--regex-JavaScript=/\.([A-Za-z0-9._$]+)[ \t]*=[ \t]*\{/\1/o,object/
--regex-JavaScript=/['"]*([A-Za-z0-9_$]+)['"]*[ \t]*:[ \t]*\{/\1/o,object/
--regex-JavaScript=/([A-Za-z0-9._$]+)\[["']([A-Za-z0-9_$]+)["']\][ \t]*=[ \t]*\{/\1\.\2/o,object/

--regex-JavaScript=/([A-Za-z0-9._$]+)[ \t]*=[ \t]*\(function\(\)/\1/c,class/
--regex-JavaScript=/['"]*([A-Za-z0-9_$]+)['"]*:[ \t]*\(function\(\)/\1/c,class/
--regex-JavaScript=/class[ \t]+([A-Za-z0-9._$]+)[ \t]*/\1/c,class/
--regex-JavaScript=/([A-Za-z$][A-Za-z0-9_$()]+)[ \t]*=[ \t]*[Rr]eact.createClass[ \t]*\(/\1/c,class/
--regex-JavaScript=/([A-Z][A-Za-z0-9_$]+)[ \t]*=[ \t]*[A-Za-z0-9_$]*[ \t]*[{(]/\1/c,class/
--regex-JavaScript=/([A-Z][A-Za-z0-9_$]+)[ \t]*:[ \t]*[A-Za-z0-9_$]*[ \t]*[{(]/\1/c,class/

--regex-JavaScript=/([A-Za-z$][A-Za-z0-9_$]+)[ \t]*=[ \t]*function[ \t]*\(/\1/f,function/

--regex-JavaScript=/(function)*[ \t]*([A-Za-z$_][A-Za-z0-9_$]+)[ \t]*\([^)]*\)[ \t]*\{/\2/f,function/
--regex-JavaScript=/['"]*([A-Za-z$][A-Za-z0-9_$]+)['"]*:[ \t]*function[ \t]*\(/\1/m,method/
--regex-JavaScript=/([A-Za-z0-9_$]+)\[["']([A-Za-z0-9_$]+)["']\][ \t]*=[ \t]*function[ \t]*\(/\2/m,method/
```

This yields _better_ behavior for some JS. It still doesn't handle your sample file correctly, but you'll get some symbols.

Parsing modern JS with regular expressions is hard. 😣

**Comment by paulodiovani** [comment] 2018-02-22 14:28
This seems to be a duplicate of #160

**Closed** 2018-02-22 15:14 UTC
Labels: enhancement
