### ISSUE TITLE
Symbol view blinks and opens after a while

### ISSUE THREAD

**Issue by Ciantic** [atom/symbols-view#91] opened 2015-04-10 05:05 UTC
I think someone broke the symbols view in latest updates.

It now blinks and the appears after a second, it's totally useless now. If I hit Ctrl+R and start typing it opens so slowly that when I type the characters still appear to editor.

Especially this problem is with TypeScript, but first and foremost it's the problem of the Symbols View UI: It should show the UI first, then load the contents, if it takes a long time to get the contents at least I can start typing already.

**Comment by izuzak** [comment] 2015-04-13 15:34
I'm not seeing that behavior, @Ciantic. Which version of Atom are you using exactly and which OS? Can you record a GIF which demonstrates the problem clearly? Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? If you can, can you share a link to the repository and file which you are reproducing this with?

**Comment by Ciantic** [comment] 2015-04-13 18:00
I recorded a GIF, it seems like it flashes a text, disappears, and re-appears.

![atom-symbols-view-blink](https://cloud.githubusercontent.com/assets/64731/7121849/1862225c-e220-11e4-9133-153345454f34.gif)

**Comment by izuzak** [comment] 2015-04-13 18:04
Thanks, @Ciantic. Can you provide answers for the other questions I asked above? That might help us investigate.

> Which version of Atom are you using exactly and which OS? Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? If you can, can you share a link to the repository and file which you are reproducing this with?

**Comment by Ciantic** [comment] 2015-04-13 18:08
Atom 0.190.0, Windows 8.1.

It doesn't happen in safe mode perhaps because there is nothing to show in the symbols view. If my guess is right, the TypeScript generates the symbols content too slowly.

**Comment by mnquintana** [comment] 2015-04-13 18:12
@Ciantic Can you post a list of your installed packages? (e.g. the output of `apm list --installed`) It would be useful to see which TypeScript package(s) we're talking about.

**Comment by izuzak** [comment] 2015-04-13 18:12
So, to be clear -- you're seeing this only with with TypeScript files or all files?

Can you share a link to the repository and file which you are reproducing this with?

**Comment by Ciantic** [comment] 2015-04-13 18:14
With all TypeScript files, you can try any .ts file or project, such as my https://github.com/Ciantic/model-validation/ with index.ts.

packages (11)
├── atom-beautify@0.24.0
├── atom-typescript@2.14.5
├── autocomplete-html@0.5.0
├── autocomplete-paths@1.0.2
├── autocomplete-plus@2.9.0
├── emmet@2.3.7
├── highlight-selected@0.9.1
├── last-cursor-position@0.8.0
├── linter@0.12.0
├── omnisharp-atom@0.2.1
└── project-manager@1.15.5

**Comment by Ciantic** [comment] 2015-04-27 11:52
I'm still experiencing this. Everything is updated. First flashes "Symbols not found", and typing is not possible, and then the real list appears.

**Comment by izuzak** [comment] 2015-04-27 12:22
@Ciantic This looks like a duplicate of https://github.com/TypeStrong/atom-typescript/issues/219. That package uses a custom symbols view (see https://github.com/TypeStrong/atom-typescript/commit/957217744c61e10d0c793785ef149fdc7bd97012 where it was added to that project). As far as I can tell, the problem you reported is not an issue in this package, but please provide more information if you believe otherwise.

**Closed by izuzak** 2015-04-27 12:22 UTC
Labels: more-information-needed
